### PR TITLE
Replace OpenStruct with Hash for performance

### PR DESCRIPTION
**Pull request by dansingerman**
Thanks to @adampal's comment here: https://github.com/bullet-train-co/bullet_train-roles/pull/21#issuecomment-1246157913 I benchmarked OpenStructs vs Hashes for this use case, and Hashes are indeed noticeable quicker.

### CODE REVIEW

**Comment by adampal** [comment]
Looks good @dansingerman .
Out of curiosity, how much faster were the hashes?

**Comment by dansingerman** [comment]
Hard to get an accurate number as the processing time (both with and without the hash) was quite variable on my local, but for a large roles.yml a call to `permit` seemed to be in the order of 25-50% quicker when reading the data from cache.

**Comment by peterkeen** [comment]
@dansingerman I'm curious what the perf difference would be if you replaced them with POROs instead. You'd need something like:

```ruby
# {is_debug: false, actions: ag.actions, model: ag.model.to_s, condition: ag.condition}

class Permission
  attr_reader :is_debug, :actions, :model, :condition, :info
  
  def initialize(is_debug: nil, actions: nil, model: nil, condition: nil, info: nil)
    @is_debug = is_debug
    @actions = actions
    @model = model
    @condition = conditions
    @info = info
  end
end

# ...

 permissions << Permission.new(is_debug: true, info: "########### ROLE: #{role.key}")
```

POROs _should_ be faster than hashes, but I wouldn't want to make that kind of change without some benchmarking. They have some good benefits wrt interface expectations as well, although this is a fairly constrained use case so that's not as strong an argument.

## Edit

I got really curious so I did a synthetic benchmark. This is `ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [arm64-darwin21]` on an M1 Macbook Pro.

```ruby
require 'benchmark'
require 'ostruct'
require 'active_support'
require 'json'

ROUNDS = 1000
RESTORE_ROUNDS = 1000

class TestClass
  attr_reader :foo, :bar

  def initialize(foo:, bar:)
    @foo = foo
    @bar = bar
  end
end

def cache_and_restore
  cache = ActiveSupport::Cache.lookup_store(:memory_store)
  1.upto(RESTORE_ROUNDS) do
    cache.fetch("some_cache_key") do
      yield
    end
  end
end

def cache_and_restore_open_struct
  cache_and_restore do
    OpenStruct.new(foo: "abc", bar: "def")
  end
end

def cache_and_restore_hash
  cache_and_restore do
    { foo: "abc", bar: "def" }
  end
end

def cache_and_restore_poro
  cache_and_restore do
    TestClass.new(foo: "abc", bar: "def")
  end
end

Benchmark.bm do |x|
  x.report("openstruct:") { 1.upto(ROUNDS) { cache_and_restore_open_struct } }
  x.report("hash:") { 1.upto(ROUNDS) { cache_and_restore_hash } }
  x.report("poro:") { 1.upto(ROUNDS) { cache_and_restore_poro } }
end
```

Results:
```
                               user     system      total        real
openstruct:  5.183252   0.038586   5.221838 (  5.225348)
hash:            4.643821   0.009718   4.653539 (  4.657105)
poro:            4.931460   0.009425   4.940885 (  4.944060)
```

In this benchmark PORO's are actually a bit slower than hashes. I don't think this is quite as representative as a benchmark with the actual code, since it appears open structs are actually somewhat competitive.

**Comment by dansingerman** [comment]
Interesting...I think it might be a more representative benchmark if you read the values from the restored object too - I suspect that is where the openstruct is significantly slower.

**Comment by dansingerman** [comment]
This seems to show more of the profile we are looking at here (far more reads of the object than cache restores):

```ruby
require 'benchmark'
require 'ostruct'
require 'active_support'
require 'json'

ROUNDS = 1000
RESTORE_ROUNDS = 100
READ_ROUNDS = 10000

class TestClass
  attr_reader :foo, :bar

  def initialize(foo:, bar:)
    @foo = foo
    @bar = bar
  end
end

def cache_and_restore
  x = nil
  cache = ActiveSupport::Cache.lookup_store(:memory_store)
  1.upto(RESTORE_ROUNDS) do
    x = cache.fetch("some_cache_key") do
      yield
    end
  end
  x
end

def cache_and_restore_and_read_open_struct
  x = cache_and_restore do
    OpenStruct.new(foo: "abc", bar: "def")
  end
  1.upto(READ_ROUNDS) do
    x.foo
    x.bar
  end
end

def cache_and_restore_and_read_hash
  x = cache_and_restore do
    { foo: "abc", bar: "def" }
  end
  1.upto(READ_ROUNDS) do
    x[:foo]
    x[:bar]
  end
end

def cache_and_restore_and_read_poro
  x = cache_and_restore do
    TestClass.new(foo: "abc", bar: "def")
  end
  1.upto(READ_ROUNDS) do
    x.foo
    x.bar
  end
end

Benchmark.bm do |x|
  x.report("openstruct:") { 1.upto(ROUNDS) { cache_and_restore_and_read_open_struct } }
  x.report("hash:") { 1.upto(ROUNDS) { cache_and_restore_and_read_hash } }
  x.report("poro:") { 1.upto(ROUNDS) { cache_and_restore_and_read_poro } }
end
```

On my 2017 imac it gives

```
       user     system      total        real
openstruct:  3.197707   0.039858   3.237565 (  3.298756)
hash:  2.005453   0.002691   2.008144 (  2.012668)
poro:  1.937997   0.095377   2.033374 (  2.270886)
```

**Comment by peterkeen** [comment]
@dansingerman ah sure, that makes sense. In any case it doesn't seem like POROs have any edge here over hashes. Thanks for indulging me in a spurious interjection :)

**Comment by adampal** [comment]
Thanks for looking into all options guys.
I'm going to merge this because it looks like we've found the best solution for this situation and all the tests are passing.
Once this is done, I'll rebase #20 and get that wrapped up.  Between these two PRs we should have a very significant speed improvement we can release as the next update.

**Pull request merged**
